name: Build and deploy
# Limit workflow to main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build static site
    runs-on: ubuntu-latest
    container:
      image: sleavely/node-awscli:14.x
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci

    - name: Build .vuepress/dist/
      run: npm run build

    - name: Upload GitHub Pages artifact
      id: deployment
      uses: actions/deploy-pages@v1
      with:
        path: .vuepress/dist/

  deploy:
    needs: build
    name: Deploy Github Pages artifact
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write
      id-token: write
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1

    - name: Print page URL
      run: |
        echo Deployed to ${{ steps.deployment.outputs.page_url }}
